allowBuilds:
  '@kmamal/gpu': set this to true or false
  esbuild: true
ignoredBuiltDependencies:
  - '@kmamal/gpu'
minimumReleaseAgeExclude:
  - '@random-mesh/rm-pan-scale@0.0.4'
  - '@solidjs/signals@2.0.0-beta.29'
  - '@solidjs/web@2.0.0-beta.29'
  - solid-js@2.0.0-beta.29
onlyBuiltDependencies:
  - esbuild
