/**
 * Regenerates src/icon-kinds.ts from the Font Awesome metadata in node_modules.
 *
 * Only the icons that the free license ships in the classic/solid style are
 * emitted, since <Icon/> always renders `fa-solid fa-${kind}`. Aliases are
 * skipped: they resolve to the same glyph as their canonical name and would
 * only pad autocompletion.
 *
 * Run with: pnpm generate:icon-kinds
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface FamilyStyle {
  family: string;
  style: string;
}

interface IconMetadata {
  familyStylesByLicense?: {
    free?: Array<FamilyStyle>;
    pro?: Array<FamilyStyle>;
  };
}

// Anchored to the repository root so the script runs from any working directory.
const ROOT = join(import.meta.dirname, "..");
const PACKAGE = join(ROOT, "node_modules/@fortawesome/fontawesome-free");
const OUTPUT = join(ROOT, "src/icon-kinds.ts");

const readJson = <T>(path: string): T => JSON.parse(readFileSync(path, "utf8"));

const { version } = readJson<{ version: string }>(join(PACKAGE, "package.json"));
const icons = readJson<Record<string, IconMetadata>>(join(PACKAGE, "metadata/icon-families.json"));

const kinds = Object.entries(icons)
  .filter(([, icon]) =>
    (icon.familyStylesByLicense?.free ?? []).some(
      ({ family, style }) => family === "classic" && style === "solid",
    ),
  )
  .map(([name]) => name)
  .sort();

const source = `// Generated by scripts/generate-icon-kinds.ts from Font Awesome Free ${version}. Do not edit.

/** Every icon name available in the free classic/solid style. */
export type IconKind =
${kinds.map(kind => `  | "${kind}"`).join("\n")};
`;

writeFileSync(OUTPUT, source);
console.log(`Wrote ${kinds.length} icon kinds to ${OUTPUT}`);
